import pytest
import asyncio
from textual.widgets import Markdown
from TUI.app import FPrimeTUI
from tests.test_helpers import submit_query

@pytest.mark.asyncio
async def test_verify_code_block_preservation(mock_ai_client):
    """
    Verifies that triple backticks generated by the AI are preserved in the chat history.
    """
    app = FPrimeTUI()
    app._show_agent_thoughts = True # Ensure we see everything

    # Simulating a response that includes a code block
    code_block_response = [
        "Here is the requested code:\n\n",
        "```cpp\n",
        "int main() {\n",
        "    return 0;\n",
        "}\n",
        "```\n",
        "Does this look correct?"
    ]
    await mock_ai_client.queue_response(code_block_response)

    async with app.run_test() as pilot:
        await pilot.pause()
        await app._mount_ai_turn("# Mission Control Online\nAwaiting command. Use `@file` or `/command`.")
        await submit_query(pilot, app, "Generate a C++ main function.")
        # Wait a bit for the async worker to finish streaming
        for _ in range(20):
            await pilot.pause(0.1)
            if "Does this look correct?" in app.chat_history:
                break
        
        # Check if the chat history contains the exact Markdown structure
        history = app.chat_history
        assert "```cpp" in history
        assert "int main() {" in history
        assert "return 0;" in history
        assert "```" in history
        assert "Does this look correct?" in history

@pytest.mark.asyncio
async def test_verify_json_tool_hiding_but_code_preservation(mock_ai_client):
    """
    Verifies that tool JSON blocks are hidden while regular code blocks are kept.
    """
    app = FPrimeTUI()
    app._show_agent_thoughts = False # Typical user mode

    # If the JSON block is at the END of a message, everything before it is kept.
    # If the JSON block is in the MIDDLE, the current logic stops displaying at the JSON block.
    mixed_response = [
        "I will show you an example and then read the file.\n\n",
        "Example code:\n",
        "```python\n",
        "print('hello')\n",
        "```\n\n",
        "Now reading tool:\n",
        "```json\n",
        '{"tool_name": "read_file", "path": "test.txt"}\n',
        "```"
    ]
    # We need to queue a second response for the tool result summary
    await mock_ai_client.queue_response(mixed_response)
    await mock_ai_client.queue_response(["Tool call finished."])

    async with app.run_test() as pilot:
        await pilot.pause(0.5)
        
        # Trigger the first stream
        await submit_query(pilot, app, "Read the file and show example.")
        
        # Wait for the first stream (which triggers the tool)
        for _ in range(20):
            await pilot.pause(0.1)
            # We wait for the text BEFORE the JSON block to appear
            if "Example code:" in app.chat_history:
                break
        
        history = app.chat_history
        
        # 1. The JSON tool block should be hidden (since _show_agent_thoughts is False)
        assert '{"tool_name": "read_file"' not in history
        
        # 2. The regular python code block SHOULD be preserved
        assert "```python" in history
        assert "print('hello')" in history
        assert "```" in history
        assert "Example code:" in history

@pytest.mark.asyncio
async def test_user_unclosed_code_block_plain_text(mock_ai_client):
    """
    Verifies that a user prompt containing backticks is rendered as plain text,
    preventing it from starting a code block that affects the AI's turn.
    """
    app = FPrimeTUI()
    app._show_agent_thoughts = True

    await mock_ai_client.queue_response(["I see you typed some backticks."])

    async with app.run_test() as pilot:
        await pilot.pause()
        await app._mount_ai_turn("# Mission Control Online\nAwaiting command. Use `@file` or `/command`.")
        # User sends a prompt with backticks
        await submit_query(pilot, app, "```")
        
        for _ in range(10):
            await pilot.pause(0.1)
            if "Mission Control:" in app.chat_history:
                break
        
        history = app.chat_history
        
        # In the new architecture, the user's ``` is plain text in a Static widget.
        # The history string still records it literally.
        assert "User: ```" in history
        assert "Mission Control:" in history
